### ISSUE TITLE
Wrong code

### ISSUE THREAD

**Issue by Attacler** [galnir/Jay-Bot#3]
This line gives an error, it might have to be }catch (err){ ?

Same on line 102,131

https://github.com/galnir/Jay-Bot/blob/b875e78a3177f34eb7c10b3f65710415545344f5/commands/play.js#L56

**Comment by galnir** [comment]
Thanks for reporting the issue! Fixed in [456e86d](https://github.com/galnir/Jay-Bot/commit/456e86d082cb4c7d7d9ed8b79ff7d46845da9307)
